In [1]:
import pandas as pd

In [4]:
population_series = pd.Series([8700000,4200000,3000000,2100000,400000],
                                index = ['USSR','Germain','China','Japan','USA'])
filtered_population=population_series[population_series>3000000]
population_dict = filtered_population.to_dict()
population_dict

{'USSR': 8700000, 'Germain': 4200000}

## Task2

In [16]:
monthly_sales = pd.Series([200, 300, None, 150, 400, None, 350, 300, 200, None, 450,500])
monthly_sales

0     200.0
1     300.0
2       NaN
3     150.0
4     400.0
5       NaN
6     350.0
7     300.0
8     200.0
9       NaN
10    450.0
11    500.0
dtype: float64

In [17]:
# Calculate AVG
avg_sale=monthly_sales.mean()
avg_sale

316.6666666666667

In [19]:
# Fill missing Value with AVG sale
monthly_sale_fill = monthly_sales.fillna(avg_sale)
monthly_sale_fill

0     200.000000
1     300.000000
2     316.666667
3     150.000000
4     400.000000
5     316.666667
6     350.000000
7     300.000000
8     200.000000
9     316.666667
10    450.000000
11    500.000000
dtype: float64

In [24]:
# Fill missing Value with two more months to the end Nan
monthly_sales_reindexed = monthly_sale_fill.reindex(range(14))
monthly_sales_reindexed

0     200.000000
1     300.000000
2     316.666667
3     150.000000
4     400.000000
5     316.666667
6     350.000000
7     300.000000
8     200.000000
9     316.666667
10    450.000000
11    500.000000
12           NaN
13           NaN
dtype: float64

In [27]:
# Fill missing Value with 0
monthly_sales_zero = monthly_sales_reindexed.fillna(0)
monthly_sales_zero

0     200.000000
1     300.000000
2     316.666667
3     150.000000
4     400.000000
5     316.666667
6     350.000000
7     300.000000
8     200.000000
9     316.666667
10    450.000000
11    500.000000
12      0.000000
13      0.000000
dtype: float64

# Task3

In [29]:
import numpy as np

In [31]:
sensor_data = pd.DataFrame({ 'Sensor_1': [25, 145, np.nan, 152, 130, np.nan, 40, 60, 180,
90], 'Sensor_2': [np.nan, 60, 75, 140, np.nan, 160, 155, 80, 110, 145], 'Sensor_3': [100,
np.nan, 135, 165, 45, 150, np.nan, 155, 120, 170], 'Sensor_4': [120, 135, 140, np.nan, 125,
180, np.nan, 70, 160, 150], 'Sensor_5': [140, np.nan, 155, 60, 175, 130, 95, np.nan, 150,
115] })
sensor_data

   Sensor_1  Sensor_2  Sensor_3  Sensor_4  Sensor_5
0      25.0       NaN     100.0     120.0     140.0
1     145.0      60.0       NaN     135.0       NaN
2       NaN      75.0     135.0     140.0     155.0
3     152.0     140.0     165.0       NaN      60.0
4     130.0       NaN      45.0     125.0     175.0
5       NaN     160.0     150.0     180.0     130.0
6      40.0     155.0       NaN       NaN      95.0
7      60.0      80.0     155.0      70.0       NaN
8     180.0     110.0     120.0     160.0     150.0
9      90.0     145.0     170.0     150.0     115.0

In [33]:
# Fill missing value
sensor_data_filled = sensor_data.apply(lambda x: x.fillna(x.mean()), axis=0)
sensor_data_filled

   Sensor_1  Sensor_2  Sensor_3  Sensor_4  Sensor_5
0     25.00   115.625     100.0     120.0     140.0
1    145.00    60.000     130.0     135.0     127.5
2    102.75    75.000     135.0     140.0     155.0
3    152.00   140.000     165.0     135.0      60.0
4    130.00   115.625      45.0     125.0     175.0
5    102.75   160.000     150.0     180.0     130.0
6     40.00   155.000     130.0     135.0      95.0
7     60.00    80.000     155.0      70.0     127.5
8    180.00   110.000     120.0     160.0     150.0
9     90.00   145.000     170.0     150.0     115.0

In [36]:
# control threshold
sensor_data_threshold = sensor_data_filled.applymap(lambda x: min(x, 150))
sensor_data_threshold

/tmp/ipykernel_30/327352651.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  sensor_data_threshold = sensor_data_filled.applymap(lambda x: min(x, 150))

   Sensor_1  Sensor_2  Sensor_3  Sensor_4  Sensor_5
0     25.00   115.625     100.0     120.0     140.0
1    145.00    60.000     130.0     135.0     127.5
2    102.75    75.000     135.0     140.0     150.0
3    150.00   140.000     150.0     135.0      60.0
4    130.00   115.625      45.0     125.0     150.0
5    102.75   150.000     150.0     150.0     130.0
6     40.00   150.000     130.0     135.0      95.0
7     60.00    80.000     150.0      70.0     127.5
8    150.00   110.000     120.0     150.0     150.0
9     90.00   145.000     150.0     150.0     115.0

# Task4

In [38]:
pixel_values = np.array([23, 45, 167, 89, 34, 120, 56, 200, 78, 144, 34, 255, 189, 67, 90,
160, 128, 45, 210, 75, 44, 88, 77, 150, 99])
pixel_values

array([ 23,  45, 167,  89,  34, 120,  56, 200,  78, 144,  34, 255, 189,
        67,  90, 160, 128,  45, 210,  75,  44,  88,  77, 150,  99])

In [41]:
# step1:Reshape 5x5
image_matrix = pixel_values.reshape(5,5)
image_matrix

array([[ 23,  45, 167,  89,  34],
       [120,  56, 200,  78, 144],
       [ 34, 255, 189,  67,  90],
       [160, 128,  45, 210,  75],
       [ 44,  88,  77, 150,  99]])

In [43]:
# Step 2: Cap values above 150( pixel values above 150 needs to be set to 150)
image_matrix = np.clip(image_matrix, 0, 150)  
image_matrix

array([[ 23,  45, 150,  89,  34],
       [120,  56, 150,  78, 144],
       [ 34, 150, 150,  67,  90],
       [150, 128,  45, 150,  75],
       [ 44,  88,  77, 150,  99]])

In [45]:
# Step 3: Extract the central 3x3 region
central_region = image_matrix[1:4, 1:4]
central_region

array([[ 56, 150,  78],
       [150, 150,  67],
       [128,  45, 150]])

# Task5

In [47]:
rainfall_data = np.array([ 45, 120, 250, 85, 60, 30, 110, 55, 40, 180, 210, 65, 95, 140, 35,
60, 220, 125, 80, 70, 90, 200, 50, 160 ])
rainfall_data

array([ 45, 120, 250,  85,  60,  30, 110,  55,  40, 180, 210,  65,  95,
       140,  35,  60, 220, 125,  80,  70,  90, 200,  50, 160])

In [49]:
# Use conditional selection to filter values between 50 and 200 mm
rainfall_filtered = rainfall_data[(rainfall_data > 50) & (rainfall_data < 200)]
rainfall_filtered

array([120,  85,  60, 110,  55, 180,  65,  95, 140,  60, 125,  80,  70,
        90, 160])